name: Test Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - arc_arc700
          - arm_cortex-a15_neon-vfpv4
          - arm_cortex-a9_neon
          - arm_cortex-a9_vfpv3-d16
          - i386_pentium4
          - mips_24kc
          - powerpc_464fp
          - powerpc_8540
          - x86_64

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine changed packages
        run: |
          # only detect packages with changed Makefiles
          PACKAGES="$(git diff --diff-filter=d --name-only origin/master \
            | grep 'Makefile$' | grep -Ev '/files/|/src/' \
            | awk -F/ '{ print $(NF-1) }' | tr '\n' ' ')"

          # fallback to test packages if nothing explicitly changes this is
          # should run if other mechanics in packages.git changed
          PACKAGES="${PACKAGES:-vim tmux bmon}"

          echo "Building $PACKAGES"
          echo "::set-env name=PACKAGES::$PACKAGES"

      - name: Build
        uses: openwrt/gh-action-sdk@v1
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: packages_ci

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk

      - name: Store logs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-logs
          path: logs/

